version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

parameters:
  #project Path

jobs:
  default-unity-win64-build:
    executor:
      name: 'unity/windows-2019'
      size: 'medium'
      editor_version: '2021.3.26f1'
      target_platform: 'windows-il2cpp'
    steps:
      # precheck for Unity Auth
      - restore_cache:
        keys:
          - unity-cache-{{ arch }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ""}}
      - checkout
      - save_cache:
        key: unity-cache-{{ arch }}-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ""}}
      - run:
        command: echo "hello world"

workflows:
  build-unity:
    jobs:
      - default-unity-win64-build:
        filters:
          branches:
            only:
              - citests